"""inital

Revision ID: a417194cb164
Revises: 
Create Date: 2026-04-02 18:47:10.577554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a417194cb164'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('django_content_type', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('django_content_type_app_label_model_76bd3d3b_uniq'))

    op.drop_table('django_content_type')
    with op.batch_alter_table('auth_permission', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('auth_permission_content_type_id_2f476e4b'))
        batch_op.drop_index(batch_op.f('auth_permission_content_type_id_codename_01ab375a_uniq'))

    op.drop_table('auth_permission')
    op.drop_table('django_migrations')
    op.drop_table('blog_location')
    with op.batch_alter_table('django_session', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('django_session_expire_date_a5c62663'))

    op.drop_table('django_session')
    with op.batch_alter_table('django_admin_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('django_admin_log_content_type_id_c4bce8eb'))
        batch_op.drop_index(batch_op.f('django_admin_log_user_id_c564eba6'))

    op.drop_table('django_admin_log')
    with op.batch_alter_table('blog_myuser_user_permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('blog_myuser_user_permissions_myuser_id_1c6bf21a'))
        batch_op.drop_index(batch_op.f('blog_myuser_user_permissions_myuser_id_permission_id_f09523ed_uniq'))
        batch_op.drop_index(batch_op.f('blog_myuser_user_permissions_permission_id_61a1da5f'))

    op.drop_table('blog_myuser_user_permissions')
    op.drop_table('auth_group')
    with op.batch_alter_table('blog_myuser_groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('blog_myuser_groups_group_id_18364efb'))
        batch_op.drop_index(batch_op.f('blog_myuser_groups_myuser_id_9b025807'))
        batch_op.drop_index(batch_op.f('blog_myuser_groups_myuser_id_group_id_2a262a29_uniq'))

    op.drop_table('blog_myuser_groups')
    with op.batch_alter_table('blog_post', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('blog_post_author_id_dd7a8485'))
        batch_op.drop_index(batch_op.f('blog_post_category_id_c326dbf8'))
        batch_op.drop_index(batch_op.f('blog_post_location_id_040b0a05'))

    op.drop_table('blog_post')
    with op.batch_alter_table('auth_group_permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('auth_group_permissions_group_id_b120cbf9'))
        batch_op.drop_index(batch_op.f('auth_group_permissions_group_id_permission_id_0cd325b0_uniq'))
        batch_op.drop_index(batch_op.f('auth_group_permissions_permission_id_84c5c92e'))

    op.drop_table('auth_group_permissions')
    with op.batch_alter_table('blog_comment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('blog_comment_author_id_4f11e2e0'))
        batch_op.drop_index(batch_op.f('blog_comment_post_id_580e96ef'))

    op.drop_table('blog_comment')
    op.drop_table('blog_category')
    with op.batch_alter_table('blog_myuser', schema=None) as batch_op:
        batch_op.alter_column('last_login',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.create_unique_constraint(None, ['username'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_myuser', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('last_login',
               existing_type=sa.DATETIME(),
               nullable=True)

    op.create_table('blog_category',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('is_published', sa.BOOLEAN(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=256), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('slug', sa.VARCHAR(length=50), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blog_comment',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('text', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('is_published', sa.BOOLEAN(), nullable=False),
    sa.Column('author_id', sa.BIGINT(), nullable=False),
    sa.Column('post_id', sa.BIGINT(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['blog_myuser.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['blog_post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('blog_comment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('blog_comment_post_id_580e96ef'), ['post_id'], unique=False)
        batch_op.create_index(batch_op.f('blog_comment_author_id_4f11e2e0'), ['author_id'], unique=False)

    op.create_table('auth_group_permissions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('group_id', sa.INTEGER(), nullable=False),
    sa.Column('permission_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['auth_group.id'], ),
    sa.ForeignKeyConstraint(['permission_id'], ['auth_permission.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('auth_group_permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('auth_group_permissions_permission_id_84c5c92e'), ['permission_id'], unique=False)
        batch_op.create_index(batch_op.f('auth_group_permissions_group_id_permission_id_0cd325b0_uniq'), ['group_id', 'permission_id'], unique=1)
        batch_op.create_index(batch_op.f('auth_group_permissions_group_id_b120cbf9'), ['group_id'], unique=False)

    op.create_table('blog_post',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('is_published', sa.BOOLEAN(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=256), nullable=False),
    sa.Column('text', sa.TEXT(), nullable=False),
    sa.Column('pub_date', sa.DATETIME(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('category_id', sa.BIGINT(), nullable=True),
    sa.Column('location_id', sa.BIGINT(), nullable=True),
    sa.Column('image', sa.VARCHAR(length=100), nullable=False),
    sa.Column('author_id', sa.BIGINT(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['blog_myuser.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['blog_category.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['blog_location.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('blog_post', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('blog_post_location_id_040b0a05'), ['location_id'], unique=False)
        batch_op.create_index(batch_op.f('blog_post_category_id_c326dbf8'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('blog_post_author_id_dd7a8485'), ['author_id'], unique=False)

    op.create_table('blog_myuser_groups',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('myuser_id', sa.BIGINT(), nullable=False),
    sa.Column('group_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['auth_group.id'], ),
    sa.ForeignKeyConstraint(['myuser_id'], ['blog_myuser.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('blog_myuser_groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('blog_myuser_groups_myuser_id_group_id_2a262a29_uniq'), ['myuser_id', 'group_id'], unique=1)
        batch_op.create_index(batch_op.f('blog_myuser_groups_myuser_id_9b025807'), ['myuser_id'], unique=False)
        batch_op.create_index(batch_op.f('blog_myuser_groups_group_id_18364efb'), ['group_id'], unique=False)

    op.create_table('auth_group',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blog_myuser_user_permissions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('myuser_id', sa.BIGINT(), nullable=False),
    sa.Column('permission_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['myuser_id'], ['blog_myuser.id'], ),
    sa.ForeignKeyConstraint(['permission_id'], ['auth_permission.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('blog_myuser_user_permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('blog_myuser_user_permissions_permission_id_61a1da5f'), ['permission_id'], unique=False)
        batch_op.create_index(batch_op.f('blog_myuser_user_permissions_myuser_id_permission_id_f09523ed_uniq'), ['myuser_id', 'permission_id'], unique=1)
        batch_op.create_index(batch_op.f('blog_myuser_user_permissions_myuser_id_1c6bf21a'), ['myuser_id'], unique=False)

    op.create_table('django_admin_log',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('action_time', sa.DATETIME(), nullable=False),
    sa.Column('object_id', sa.TEXT(), nullable=True),
    sa.Column('object_repr', sa.VARCHAR(length=200), nullable=False),
    sa.Column('change_message', sa.TEXT(), nullable=False),
    sa.Column('content_type_id', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('action_flag', sa.INTEGER(), nullable=False),
    sa.CheckConstraint('"action_flag" >= 0'),
    sa.ForeignKeyConstraint(['content_type_id'], ['django_content_type.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['blog_myuser.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('django_admin_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('django_admin_log_user_id_c564eba6'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('django_admin_log_content_type_id_c4bce8eb'), ['content_type_id'], unique=False)

    op.create_table('django_session',
    sa.Column('session_key', sa.VARCHAR(length=40), nullable=False),
    sa.Column('session_data', sa.TEXT(), nullable=False),
    sa.Column('expire_date', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('session_key')
    )
    with op.batch_alter_table('django_session', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('django_session_expire_date_a5c62663'), ['expire_date'], unique=False)

    op.create_table('blog_location',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('is_published', sa.BOOLEAN(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=256), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('django_migrations',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('app', sa.VARCHAR(length=255), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('applied', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auth_permission',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('content_type_id', sa.INTEGER(), nullable=False),
    sa.Column('codename', sa.VARCHAR(length=100), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.ForeignKeyConstraint(['content_type_id'], ['django_content_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('auth_permission', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('auth_permission_content_type_id_codename_01ab375a_uniq'), ['content_type_id', 'codename'], unique=1)
        batch_op.create_index(batch_op.f('auth_permission_content_type_id_2f476e4b'), ['content_type_id'], unique=False)

    op.create_table('django_content_type',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('app_label', sa.VARCHAR(length=100), nullable=False),
    sa.Column('model', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('django_content_type', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('django_content_type_app_label_model_76bd3d3b_uniq'), ['app_label', 'model'], unique=1)

    # ### end Alembic commands ###
