"""добавил авторизацию и аутентификацию всех необходимых апи роутов

Revision ID: ef9faf321940
Revises: e9761769772e
Create Date: 2026-04-27 22:16:10.704625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef9faf321940'
down_revision: Union[str, Sequence[str], None] = 'e9761769772e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
